-- Compatibility entry points for schemas generated by Wanxiang <= 17.5.
--
-- The user-prediction module was removed upstream.  A stale librime build can
-- nevertheless still refer to it until the deployment is rebuilt.  Keep the
-- old component names loadable and leave the normal candidate stream intact;
-- the current schema does not reference this module.

local P = {}
function P.func(_key, _env)
    -- ProcessResult::kNoop.
    return 2
end

local T = {}
function T.func(_input, _segment, _env)
    -- No compatibility predictions are generated.
end

local F = {}
function F.func(input, _env)
    for cand in input:iter() do
        yield(cand)
    end
end

return { P = P, T = T, F = F }
